import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

// {a.b.c} -> var(--a-b-c) ; literal lain apa adanya
export function resolveValue(raw) {
  const m = /^\{([^}]+)\}$/.exec(String(raw).trim());
  return m ? `var(--${m[1].replace(/\./g, '-')})` : String(raw);
}

// leaf = objek dengan $value ; name = path digabung '-'
export function flatten(tokens, prefix = []) {
  const out = [];
  for (const [key, val] of Object.entries(tokens)) {
    if (val && typeof val === 'object' && '$value' in val) {
      out.push({
        name: [...prefix, key].join('-'),
        value: val.$value,
        dark: val.$dark,
        compact: val.$compact,
      });
    } else if (val && typeof val === 'object') {
      out.push(...flatten(val, [...prefix, key]));
    }
  }
  return out;
}

const decl = (name, raw) => `  --${name}: ${resolveValue(raw)};`;

export function buildTokensCss(tokens) {
  const flat = flatten(tokens);
  const root = flat.map(t => decl(t.name, t.value)).join('\n');
  const darkTokens = flat.filter(t => t.dark !== undefined);
  const dark = darkTokens.map(t => decl(t.name, t.dark)).join('\n');
  const lightReassert = darkTokens.map(t => decl(t.name, t.value)).join('\n');
  const compactTokens = flat.filter(t => t.compact !== undefined);
  const compact = compactTokens.map(t => decl(t.name, t.compact)).join('\n');
  /* The counterpart, DERIVED from the same tokens' defaults rather than restated: same key set by
     construction, so a token that gains a $compact value automatically gains its way back out, and
     a retuned default can never leave the two blocks disagreeing. */
  const comfortable = compactTokens.map(t => decl(t.name, t.value)).join('\n');

  return `/* Freeday tokens — GENERATED by tokens/build.mjs. Do not edit by hand. */
:root {
${root}
}
/* The SYSTEM default stays root-scoped: it is a statement about the document, and dropping :root
 * here would match every element that is not itself [data-theme="light"], which would re-darken
 * the children of a light panel, since they carry no attribute of their own. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark}
  }
}
/* The two EXPLICIT opt-ins are deliberately NOT scoped to :root, for the same reason as density
 * below: these are inheriting custom properties, so data-theme on any ancestor re-themes just that
 * subtree, a dark brand panel beside a light form is an ordinary layout, and it should not require
 * re-colouring each component by hand. The root still matches, so data-theme on <html> is unchanged.
 * Both keep the same specificity (0,1,0) as :root and come after it, so they still win there; and
 * --light after --dark means a light island inside a dark region wins in turn. */
[data-theme="dark"] {
${dark}
}
[data-theme="light"] {
${lightReassert}
}
/* Density is deliberately NOT scoped to :root. These are custom properties, so they inherit —
 * putting the attribute on any ancestor (a route wrapper, one section) densifies just that
 * subtree, which is how density is actually decided: per screen, not per app. The root still
 * matches, so setting data-density on the html element keeps working exactly as before. */
[data-density="compact"] {
${compact}
}
/* ...and the way back out. Inheritance only runs downhill: once the root is compact every subtree is
 * compact, and before this rule existed a data-density="comfortable" wrapper matched nothing, so the
 * comment above was true in one direction only. An app that is dense overall and carries one region
 * of shared chrome (a header, a toolbar, a footer shared with a sibling product) had to restate the
 * defaults by hand, which is exactly the local copy that goes stale when the kit retunes them. */
[data-density="comfortable"] {
${comfortable}
}
`;
}

export function bundleCss(parts) {
  return `/* Freeday components — GENERATED by tokens/build.mjs. Do not edit by hand. */\n`
    + parts.map(p => p.trim()).join('\n\n') + '\n';
}

export function bundleJs(parts) {
  return `/* Freeday enhancers — GENERATED by tokens/build.mjs. Do not edit by hand.\n`
    + ` * Concatenation of every src/*.js enhancer (each a self-contained IIFE). */\n`
    + parts.map(p => p.trim()).join('\n\n') + '\n';
}

// Single-import CSS: tokens + components in one file (so `import 'freeday/css'`
// brings everything, avoiding the "forgot the tokens" footgun).
export function bundleFullCss(tokensCss, componentsCss) {
  return `/* Freeday — tokens + components in one file. GENERATED by tokens/build.mjs. */\n`
    + tokensCss.trim() + '\n\n' + componentsCss.trim() + '\n';
}

export function main() {
  const here = dirname(fileURLToPath(import.meta.url));
  const root = join(here, '..');
  const tokens = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));
  const css = buildTokensCss(tokens);
  mkdirSync(join(root, 'dist'), { recursive: true });
  writeFileSync(join(root, 'dist/freeday.tokens.css'), css);
  console.log('Wrote dist/freeday.tokens.css');

  const base = readFileSync(join(root, 'src/base.css'), 'utf8');
  const compDir = join(root, 'src/components');
  const components = readdirSync(compDir)
    .filter(f => f.endsWith('.css')).sort()
    .map(f => readFileSync(join(compDir, f), 'utf8'));
  const componentsCss = bundleCss([base, ...components]);
  writeFileSync(join(root, 'dist/freeday.css'), componentsCss);
  console.log('Wrote dist/freeday.css');

  writeFileSync(join(root, 'dist/freeday.bundle.css'), bundleFullCss(css, componentsCss));
  console.log('Wrote dist/freeday.bundle.css');

  // Copy optional JS enhancers (authored in src/, shipped as-is) to dist,
  // and also emit a single concatenated bundle for one-tag project consumption.
  const jsFiles = readdirSync(join(root, 'src')).filter(f => f.endsWith('.js')).sort();
  const jsSources = [];
  for (const f of jsFiles) {
    const src = readFileSync(join(root, 'src', f), 'utf8');
    jsSources.push(src);
    writeFileSync(join(root, 'dist', f), src);
    console.log('Wrote dist/' + f);
  }
  writeFileSync(join(root, 'dist/freeday.js'), bundleJs(jsSources));
  console.log('Wrote dist/freeday.js');
}

if (fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
