import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

// {a.b.c} -> var(--a-b-c) ; literal lain apa adanya
export function resolveValue(raw) {
  const m = /^\{([^}]+)\}$/.exec(String(raw).trim());
  return m ? `var(--${m[1].replace(/\./g, '-')})` : String(raw);
}

// leaf = objek dengan $value ; name = path digabung '-'
export function flatten(tokens, prefix = []) {
  const out = [];
  for (const [key, val] of Object.entries(tokens)) {
    if (val && typeof val === 'object' && '$value' in val) {
      out.push({
        name: [...prefix, key].join('-'),
        value: val.$value,
        dark: val.$dark,
        compact: val.$compact,
      });
    } else if (val && typeof val === 'object') {
      out.push(...flatten(val, [...prefix, key]));
    }
  }
  return out;
}

const decl = (name, raw) => `  --${name}: ${resolveValue(raw)};`;

export function buildTokensCss(tokens) {
  const flat = flatten(tokens);
  const root = flat.map(t => decl(t.name, t.value)).join('\n');
  const darkTokens = flat.filter(t => t.dark !== undefined);
  const dark = darkTokens.map(t => decl(t.name, t.dark)).join('\n');
  const lightReassert = darkTokens.map(t => decl(t.name, t.value)).join('\n');
  const compactTokens = flat.filter(t => t.compact !== undefined);
  const compact = compactTokens.map(t => decl(t.name, t.compact)).join('\n');

  return `/* Freeday tokens — GENERATED by tokens/build.mjs. Do not edit by hand. */
:root {
${root}
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark}
  }
}
:root[data-theme="dark"] {
${dark}
}
:root[data-theme="light"] {
${lightReassert}
}
:root[data-density="compact"] {
${compact}
}
`;
}

export function bundleCss(parts) {
  return `/* Freeday components — GENERATED by tokens/build.mjs. Do not edit by hand. */\n`
    + parts.map(p => p.trim()).join('\n\n') + '\n';
}

export function bundleJs(parts) {
  return `/* Freeday enhancers — GENERATED by tokens/build.mjs. Do not edit by hand.\n`
    + ` * Concatenation of every src/*.js enhancer (each a self-contained IIFE). */\n`
    + parts.map(p => p.trim()).join('\n\n') + '\n';
}

// Single-import CSS: tokens + components in one file (so `import 'freeday/css'`
// brings everything, avoiding the "forgot the tokens" footgun).
export function bundleFullCss(tokensCss, componentsCss) {
  return `/* Freeday — tokens + components in one file. GENERATED by tokens/build.mjs. */\n`
    + tokensCss.trim() + '\n\n' + componentsCss.trim() + '\n';
}

export function main() {
  const here = dirname(fileURLToPath(import.meta.url));
  const root = join(here, '..');
  const tokens = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));
  const css = buildTokensCss(tokens);
  mkdirSync(join(root, 'dist'), { recursive: true });
  writeFileSync(join(root, 'dist/freeday.tokens.css'), css);
  console.log('Wrote dist/freeday.tokens.css');

  const base = readFileSync(join(root, 'src/base.css'), 'utf8');
  const compDir = join(root, 'src/components');
  const components = readdirSync(compDir)
    .filter(f => f.endsWith('.css')).sort()
    .map(f => readFileSync(join(compDir, f), 'utf8'));
  const componentsCss = bundleCss([base, ...components]);
  writeFileSync(join(root, 'dist/freeday.css'), componentsCss);
  console.log('Wrote dist/freeday.css');

  writeFileSync(join(root, 'dist/freeday.bundle.css'), bundleFullCss(css, componentsCss));
  console.log('Wrote dist/freeday.bundle.css');

  // Copy optional JS enhancers (authored in src/, shipped as-is) to dist,
  // and also emit a single concatenated bundle for one-tag project consumption.
  const jsFiles = readdirSync(join(root, 'src')).filter(f => f.endsWith('.js')).sort();
  const jsSources = [];
  for (const f of jsFiles) {
    const src = readFileSync(join(root, 'src', f), 'utf8');
    jsSources.push(src);
    writeFileSync(join(root, 'dist', f), src);
    console.log('Wrote dist/' + f);
  }
  writeFileSync(join(root, 'dist/freeday.js'), bundleJs(jsSources));
  console.log('Wrote dist/freeday.js');
}

if (fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
